language: node_js
node_js:
- 0.12
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: vilson@void.cc
  api_key:
    secure: jxjXq58LFEXWiZde4WF9Q3E8gOwyzdVNJmcv4AG8X3UVFS4D5eruw9z1KVY6VAZNUBejbZ589J6sxzHL2dvyWXy3f7tI1xzrD8spbB4ffMs3YlGfwnoYua+LD1D9RjZJzhFreEHnoKlXmYm3juXCLWNnWi2+4iKlWjzzQPG26XPd8CdyasO7ICBlBVyPIeKpy/5K1euHdWG6i7creDXjQRUKFHDJMDQ9TRvd19ftgGjce+5a1PR6vlbn2mlpX+U720bVRwK7ZiziAvSVesGyHyXL6shxSd1KHlTzhtDeIGQepjTojVIHQhO0KiogsLyfhQxD7dzSlLYP86tJh8SUNZxAR34CXF8LUg4eAkpl8oGjKjSzrE6HeMcMWHghxLRJwNFnI0yNfhUV5OcevXVg13NZF6mHgSWN4yA2hKKn74YrcmvRClY/+ZvugqPNaHQpUgC664+p1/optdDrqACguU/LQkAtFjkKZHPaeSh7/hUpIyK7TkoZeCNvSWprweyj/gscU0k92ooCy5AvUIRxuET8Z01gmq+0L4Nna9+bgmqYxtbqMDu/a63MgFkL1tLIqZRCaDkmoyZT5ictrmZV/5jmlxMiJ0ioU24r4xso9pkz2JcnrWG2rgLo7QJeGh2zRYLcBC60wWO1WPsXQFnMvYdb2BPkzKGNnbqqLcAKHi4=
  on:
    tags: true
    repo: noflo/noflo-filetype
